# Generated by Django 4.2 on 2023-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField()),
                ('status', models.CharField(choices=[('live', 'Live'), ('pending', 'Pending'), ('archived', 'Archived')], max_length=10)),
                ('tasks', models.ManyToManyField(to='interview_task.task')),
            ],
        ),
    ]
